## Common Templates
x-klipper-svc: &klipper-svc
  image: mkuf/klipper:latest
  restart: unless-stopped
  logging:
    driver: none
  depends_on:
    init:
      condition: service_completed_successfully
  command: -I run/klipper.tty -a run/klipper.sock cfg/printer.cfg -l log/klippy.log

## Service Definitions
services:

  ## Klippy Services
  ##
  klipper-delta:
    <<: *klipper-svc
    volumes:
      - /opt/printers/rotary-delta/config:/opt/cfg
      - run-delta:/opt/run
      - /opt/printers/rotary-delta/gcode:/opt/gcode
      - log-delta:/opt/log
    profiles:
      - fluidd
      - mainsail
      - klipperscreen

  ## WebApi
  ##
  moonraker:
    image: mkuf/moonraker:latest
    restart: unless-stopped
    pid: host
    logging:
      driver: none
    command: -c cfg/moonraker.cfg -l log/moonraker.log
    depends_on:
      init:
        condition: service_completed_successfully
      klipper:
        condition: service_started
    volumes:
      - /dev/null:/opt/klipper/config/null
      - /dev/null:/opt/klipper/docs/null
      - /run/dbus:/run/dbus
      - /run/systemd:/run/systemd
      - run-delta:/opt/run
      - /opt/printers/rotary-delta/gcode:/opt/gcode
      - log-delta:/opt/log
      - moonraker-db-delta:/opt/db
      - /opt/printers/rotary-delta/config:/opt/cfg
    profiles:
      - fluidd
      - mainsail
      - klipperscreen
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.moonraker.loadbalancer.server.port=7125"
      - "traefik.http.routers.moonraker.rule=PathPrefix(`/websocket`,`/printer`,`/api`,`/access`,`/machine`,`/server`)"
      - "traefik.http.routers.moonraker.entrypoints=web"

  ## Frontends
  ##
  fluidd:
    image: cadriel/fluidd:latest
    restart: unless-stopped
    profiles:
      - fluidd
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.fluidd.loadbalancer.server.port=80"
      - "traefik.http.routers.fluidd.rule=PathPrefix(`/`)"
      - "traefik.http.routers.fluidd.entrypoints=web"

  mainsail:
    image: ghcr.io/mainsail-crew/mainsail:edge
    restart: unless-stopped
    profiles:
      - mainsail
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.mainsail.loadbalancer.server.port=80"
      - "traefik.http.routers.mainsail.rule=PathPrefix(`/`)"
      - "traefik.http.routers.mainsail.entrypoints=web"

  klipperscreen:
    image: mkuf/klipperscreen:latest
    restart: unless-stopped
    network_mode: host
    profiles:
      - klipperscreen
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /opt/printers/rotary-delta/config:/opt/cfg

  ## Accompanying Services/Infra
  ##

  ## Config dir needs to be writable by uid/gid 1000
  ## This container sets the right permissions and exits
  init:
    image: busybox:latest
    command: chown -R 1000:1000 /prind/*
    volumes:
      - /opt/printers:/prind

  ## Loadbalancer/Proxy
  traefik:
    image: traefik:v2.5
    command:
      - "--accesslog"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  run-delta:
    driver_opts:
      type: tmpfs
      device: tmpfs
  moonraker-db-delta:
  log-delta:
    driver_opts:
      type: tmpfs
      device: tmpfs
