## Common Templates
x-klipper-svc: &klipper-svc
  build:
    context: docker/klipper
    target: run
  restart: unless-stopped
  logging:
    driver: none
  command: -I run/klipper.tty -a run/klipper.sock cfg/printer.cfg -l log/klippy.log

## Service Definitions
services:
  ## Klippy Services
  ##
  klipper-delta:
    <<: *klipper-svc
    volumes:
      - /opt/printers/rotary-delta/config:/opt/cfg
      - run-delta:/opt/run
      - /opt/printers/rotary-delta/gcode:/opt/gcode
      - log-delta:/opt/log
      - /opt/printers/rotary-delta/klipper:/opt/klipper
    profiles:
      - fluidd
      - mainsail
    network_mode: host

  klipper-vzbot:
    <<: *klipper-svc
    volumes:
      - /opt/printers/vzbot-235/config:/opt/cfg
      - run-vzbot:/opt/run
      - /opt/printers/vzbot-235/gcode:/opt/gcode
      - log-vzbot:/opt/log
    profiles:
      - fluidd
      - mainsail
    network_mode: host

  ## WebApi
  ##
  moonraker-delta:
    image: mkuf/moonraker:latest
    restart: unless-stopped
    pid: host
    logging:
      driver: none
    command: -c cfg/moonraker.cfg -l log/moonraker.log
    depends_on:
      klipper-delta:
        condition: service_started
    volumes:
      - /dev/null:/opt/klipper/config/null
      - /dev/null:/opt/klipper/docs/null
      - /run/dbus:/run/dbus
      - /run/systemd:/run/systemd
      - run-delta:/opt/run
      - /opt/printers/rotary-delta/gcode:/opt/gcode
      - log-delta:/opt/log
      - moonraker-db-delta:/opt/db
      - /opt/printers/rotary-delta/config:/opt/cfg
    profiles:
      - fluidd
      - mainsail
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.moonraker.loadbalancer.server.port=7125"
      - "traefik.http.routers.moonraker.rule=PathPrefix(`/websocket`,`/printer`,`/api`,`/access`,`/machine`,`/server`)"
      - "traefik.http.routers.moonraker.entrypoints=web"
      
  
  moonraker-vzbot:
    image: mkuf/moonraker:latest
    restart: unless-stopped
    pid: host
    logging:
      driver: none
    command: -c cfg/moonraker.cfg -l log/moonraker.log
    depends_on:
      klipper-vzbot:
        condition: service_started
    volumes:
      - /dev/null:/opt/klipper/config/null
      - /dev/null:/opt/klipper/docs/null
      - /run/dbus:/run/dbus
      - /run/systemd:/run/systemd
      - run-delta:/opt/run
      - /opt/printers/rotary-delta/gcode:/opt/gcode
      - log-delta:/opt/log
      - moonraker-db-delta:/opt/db
      - /opt/printers/rotary-delta/config:/opt/cfg
    profiles:
      - fluidd
      - mainsail
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.moonraker.loadbalancer.server.port=7125"
      - "traefik.http.routers.moonraker.rule=PathPrefix(`/websocket`,`/printer`,`/api`,`/access`,`/machine`,`/server`)"
      - "traefik.http.routers.moonraker.entrypoints=vzbot"

  ## Frontends
  ##
  fluidd:
    image: cadriel/fluidd:latest
    restart: unless-stopped
    profiles:
      - fluidd
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.fluidd.loadbalancer.server.port=80"
      - "traefik.http.routers.fluidd.rule=PathPrefix(`/`)"
      - "traefik.http.routers.fluidd.entrypoints=web"

  mainsail:
    image: ghcr.io/mainsail-crew/mainsail:edge
    restart: unless-stopped
    profiles:
      - mainsail
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.mainsail.loadbalancer.server.port=80"
      - "traefik.http.routers.mainsail.rule=PathPrefix(`/`)"
      - "traefik.http.routers.mainsail.entrypoints=web"

  klipperscreen:
    image: mkuf/klipperscreen:latest
    restart: unless-stopped
    network_mode: host
    profiles:
      - fluidd
      - mainsail
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /opt/printers/rotary-delta/config:/opt/cfg

  ## Accompanying Services/Infra
  ##

  ## Config dir needs to be writable by uid/gid 1000

  ## Loadbalancer/Proxy
  traefik:
    image: traefik:v2.5
    command:
      - "--accesslog"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.vzbot.address=:7126
    ports:
      - "80:80"
      - "7126:7126"
    restart: unless-stopped
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  run-vzbot:
    driver_opts:
      type: tmpfs
      device: tmpfs
  run-delta:
    driver_opts:
      type: tmpfs
      device: tmpfs
  moonraker-db-vzbot:
  moonraker-db-delta:
  log-vzbot:
    driver_opts:
      type: tmpfs
      device: tmpfs
  log-delta:
    driver_opts:
      type: tmpfs
      device: tmpfs
