services:
  make:
    image: mkuf/klipper:${TAG:-latest}-mcu
    tty: true
    privileged: true
    entrypoint: make
    working_dir: /opt/klipper
    volumes:
      - /dev:/dev
      - ./out:/opt/klipper/out
      - /opt/printers/rotary-delta/klipper:/opt/klipper
